version: '3.4'

services:
  zippay.users.api:
    image: ${DOCKER_REGISTRY-}zippayusersapi
    build:
      context: .
      dockerfile: ZipPay.Users.Api/Dockerfile
    expose:
      - "80"
    ports:
      - "5101:80"
    depends_on:
      - sql.data
  
  sql.data:
      image: "mcr.microsoft.com/mssql/server"
      environment:
        - SA_PASSWORD=testUser@12345
        - ACCEPT_EULA=Y
      ports:
        - "5434:1433"
